/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("./models/laptop.gltf");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Keyboard.geometry}
                material={materials.MacBookPro}
                position={[-0.55, -0.06, 0]}
                scale={[1.22, 0.03, 1.78]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen.geometry}
                material={materials.MacBookPro}
                position={[0.67, 0.07, 0]}
                rotation={[0, 0, -Math.PI]}
                scale={[-0.02, -1.19, -1.79]}
            />
        </group>
    );
}

useGLTF.preload("./models/laptop.gltf");
